### ISSUE TITLE
not working with docker-composer.yml version 3.x syntax

### ISSUE THREAD

**Issue by shopapps** [ayufan/auto-proxy#3]
Hi,

i have a question that I hope you can help with.

i have the following .yml:

```
version: "3.7"

services:
  db:
    image: mysql
    restart: always
    ports:
      - "3306"
    environment:
      MYSQL_DATABASE: homestead 
      MYSQL_ROOT_PASSWORD: test 
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      VIRTUAL_HOST: "evolve-mysql.rdc" 
    volumes:
      - mysql-data:/var/lib/mysql
  web:
    image: hitalos/laravel:latest
    ports:
      - 80
    expose:
      - 80
    volumes:
      - ./:/var/www
    links:
      - db
    environment:
      MYSQL_HOST: db
      SITE_ENV: local
      DB_HOST: db
      DB_DATABASE: homestead
      DB_USERNAME: homestead
      DB_PASSWORD: secret
      DB_CONNECTION: mysql
      #VIRTUAL_PROTO: https
      ENABLE_HTTP: 'true'
      VIRTUAL_HOST: "evolve.rdc"
    # Extra for wkhtmltopdf to access host itself
    extra_hosts:
      - "evolve.rdc:127.0.0.1" 

volumes:
  mysql-data:
```

1) if i try to browse https://evolve.rdc it eventually errors (502) 
2) if i try to browse direct e.g. http://evolve.rdc:32838 i can see the application is ok
3) if i remove the "version" reference (i.e. default to version 1) and "services" and "volumes", then the proxy does work ok 

What config am i missing to make this work with version 3 syntax in the docker-compose.yml??

many thanks for any help you can give.
